### PR TITLE
Go 1.5 with vendored dependencies

### PR DESCRIPTION
**Pull request by rhcarvalho**
Since we found some potential for this example to stop working without notice, and vendoring is a common practice in Go, I ran a quick experiment on how it could help us in making this example more self-contained.

I opted for an explicit Dockerfile and moved away from the `-onbuild` image because:
1. the `-onbuild` variant doesn't work well with vendored code;
2. we are already using Docker build strategy (because we need to set the USER); and
3. the Dockerfile in the template would be too lengthy and hard to read.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@mfojtik wdyt?

**Comment by rhcarvalho** [comment]
@mfojtik bump

**Comment by mfojtik** [comment]
@rhcarvalho LGTM, thanks for fixing this.

**Comment by rhcarvalho** [comment]
Eventually, this PR is also fixing a bug introduced by a change in exported fields in beego's Controller type:
https://bugzilla.redhat.com/show_bug.cgi?id=1300214
https://github.com/astaxie/beego/pull/1540

**Pull request merged**
