### PR TITLE
Bump to 1.8

### PR DESCRIPTION
**Pull request by Fale**

### CODE REVIEW

**Comment by agajdosi** [comment]
Is there a reason why not to bump to latest `1.10`?

**Comment by Fale** [comment]
The only one is that when I proposed it 1.8 was the latest ;)

**Comment by agajdosi** [comment]
@Fale Sorry, I have missed the year completely :sweat_smile:

**Comment by agajdosi** [comment]
WDYT about upgrade to `go v1.10` @bparees?

**Comment by bparees** [comment]
@agajdosi sure.

**Comment by agajdosi** [comment]
@bparees had some time last week, so I have created PR for bump up to `go1.11` - https://github.com/openshift/golang-ex/pull/24, take a look when you have time :)

**Pull request closed without merging**
